DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS rating
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    rating          INTEGER NOT NULL REFERENCES rating(id),
    description     VARCHAR(256) NOT NULL,
    release_date    DATE NOT NULL,
    duration        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(128) NOT NULL,
    login           VARCHAR(128) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    birthday	    DATE
);

CREATE TABLE IF NOT EXISTS genre
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id         INTEGER NOT NULL REFERENCES film(id),
    genre_id        INTEGER NOT NULL REFERENCES genre(id)
);



CREATE TABLE IF NOT EXISTS likes
(
    film_id         INTEGER NOT NULL REFERENCES film(id),
    user_id         INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id             INTEGER NOT NULL REFERENCES users(id),
    friend_id           INTEGER NOT NULL REFERENCES users(id),
    is_confirmed        BOOLEAN
);