DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS mpa
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    mpa             INTEGER NOT NULL REFERENCES mpa(id) ON DELETE CASCADE,
    description     VARCHAR(256) NOT NULL,
    release_date    DATE NOT NULL,
    duration        INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(128) NOT NULL,
    login           VARCHAR(128) NOT NULL,
    name            VARCHAR(128) NOT NULL,
    birthday	    DATE
);

CREATE TABLE IF NOT EXISTS genre
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id         INTEGER NOT NULL REFERENCES film(id) ON DELETE CASCADE,
    genre_id        INTEGER NOT NULL REFERENCES genre(id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS likes
(
    film_id         INTEGER NOT NULL REFERENCES film(id) ON DELETE CASCADE,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    friend_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_confirmed        BOOLEAN
);